
version: '3'
services:
  wanglab-jupyter-tf-template:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: wanglab-jupyter-pytorch-template
    volumes:
      - .:/home/jovyan/work:rw
    ports:
    - "9000:9000"
    restart: unless-stopped
    command: jupyter lab --ip='*' --port=9000 --no-browser --NotebookApp.token='${LOGINPASSWORD:-PASSWORD}' --allow-root
    deploy:
     resources:
      reservations:
        devices:
          - driver: nvidia
            capabilities: [gpu]
      limits:
        memory: 16000M
    environment:
      VIRTUAL_HOST: jupytertemplate.wanglab.science
      VIRTUAL_PORT: 9000
      LETSENCRYPT_HOST: jupytertemplate.wanglab.science
      LETSENCRYPT_EMAIL: mwang87@gmail.com